Changing fig to docker-compose #16
Fallback to use fig if installed but echo a notice.

diff --git a/lib/bowline/bowline b/lib/bowline/bowline
--- a/lib/bowline/bowline
+++ b/lib/bowline/bowline
@@ -41,6 +41,13 @@ bowline_init () {
     fi
   fi
   DCOMPOSE="$DCOMPOSE -p $SLUG"
+      DCOMPOSE="fig -f docker-compose.yml"
+    else
+      echo "Docker Compose is required for using Bowline"
+      exit 1
+    fi
+    echo "https://docs.docker.com/compose/install/"
+  fi
 
   cd $GIT_ROOT
 
